``Programs: FUZZY EQUIVALENCE RELATIONS
Pratibha Bhandari(22-14-03)
M.Tech.(Modelling and Simulation)
First year(Second semester)
``

In [23]:
##Program for reflexive and symmetric and transitive condition for a crisp set
import numpy as np 
def is_ref_sym(A,n):
    r=0
    #s=0
    print("The matrix under observation is : \n",A)
    B=np.zeros((n,n),int)
    for i in range(0,n):
        if A[i][i]==1:
            r+=1
        for j in range(0,n):
            B[i][j]=A[j][i]
    print("The transpose of matrix under observation is : \n",B)
    #print(np.array_equiv(A.transpose(),A))
                
    if np.array_equiv(A,B) and (r==n):
        return("Reflexive and Symmetric")
    elif np.array_equiv(A,B) and (r!=n):
        return("Only symmetric")
    elif r==n and not np.array_equiv(A,B):
        return("Only reflexive")
    else:
        return("neither symmetric nor reflexive")
    
def is_trans(A,n):
    flag=0
    for i in range(0,n):
        for j in range(0,n):
            for k in range(0,n):
                if (A[i][j]==1) and (A[j][k]==1):
                    if (A[i][k]==1):
                        continue
                    else:
                        flag=1
    if flag==1:
        return("Not Transitive")
    else:
        return("Transitive")
                
    

arr=np.array([[1,1,0,0,1],[1,1,0,0,1],[0,0,1,0,0],[0,0,0,1,0]\
              ,[1,1,0,0,1]])
print("The given array is",is_ref_sym(arr,len(arr[0:])),"and"\
      ,is_trans(arr,len(arr[0:])))



The matrix under observation is : 
 [[1 1 0 0 1]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 1 0 0 1]]
The transpose of matrix under observation is : 
 [[1 1 0 0 1]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 1 0 0 1]]
The given array is Reflexive and Symmetric and Transitive


In [24]:
#Program to calculate max-min matrix product
import numpy as np
A=np.array([[0.4,0.7,1.0]])
mA=np.array(A.shape)
print("The matrix A is:\n ",A)
print("The no. of rows and columns in matrix A is given by:\n",mA[0],"*",mA[1])
B=np.array([[0.1,0.1],[0.3,0.5],[0.3,0.8]])
mB=np.array(B.shape)
print("The matrix B is:\n ",B)
print("The no. of rows and columns in matrix B is given by:\n",mB[0],"*",mB[1])
if mA[1]==mB[0]:
    C=np.zeros((mA[0],mB[1]))
    for i in range(0,mA[0]):
        for j in range(0,mB[1]):
            for k in range(0,mB[0]):
                C[i][j]=max(C[i][j],min(A[i][k],B[k][j]))
print("The min-max product of the matrix (A*B) is given by: \n",C)

The matrix A is:
  [[0.4 0.7 1. ]]
The no. of rows and columns in matrix A is given by:
 1 * 3
The matrix B is:
  [[0.1 0.1]
 [0.3 0.5]
 [0.3 0.8]]
The no. of rows and columns in matrix B is given by:
 3 * 2
The min-max product of the matrix (A*B) is given by: 
 [[0.3 0.8]]


In [25]:
##Program for reflexive and symmetric and transitive condition for a fuzzy set
import numpy as np
def fuzz_ref(A,n):
    r=0
    for i in range(0,n):
        if A[i][i]==1:
            r+=1
    if r==n:
        return("Reflexive relation")
    else:
        return("not a Reflexive relation")
def fuzz_sym(A,n):
    B=A.T
    if np.array_equiv(A,B):
        return("Symmetric relation")
    else:
        return("not a symmetric relation")
def fuzz_trans(A,n):
    flag=0
    for i in range(0,n):
        for j in range(0,n):
            for k in range(0,n):
                if A[i][k]>=min(A[i][j],A[j][k]):
                    continue
                else:
                    flag=1
    if flag==0:
        return("Transitive relation")
    else:
        return("Not a Transitive relation")

            
A=np.array([[1,0.83,0.91,0.68,0.98],[0.83,1,0.93,0.6,0.74],[0.91,0.93,1,0.44,0.82]\
            ,[0.68,0.6,0.44,1,0.77],[0.98,0.74,0.82,0.77,1]])
n=5
print("The matrix under consideration to check equivalence relation:\n",A)
print("The given fuzzy relation is ",fuzz_ref(A,n),"and",fuzz_sym(A,n)\
      ,"and",fuzz_trans(A,n))
if fuzz_ref(A,n)=="Reflexive relation" and fuzz_sym(A,n)=="Symmetric relation"\
and fuzz_trans(A,n)=="Transitive relation" :
    print("The given relation is an equivalence relation")
    

The matrix under consideration to check equivalence relation:
 [[1.   0.83 0.91 0.68 0.98]
 [0.83 1.   0.93 0.6  0.74]
 [0.91 0.93 1.   0.44 0.82]
 [0.68 0.6  0.44 1.   0.77]
 [0.98 0.74 0.82 0.77 1.  ]]
The given fuzzy relation is  Reflexive relation and Symmetric relation and Not a Transitive relation


In [26]:
#To obtain the transitive matrix from a non transitive matrix 
#(provided the matrix is both reflexive and symmetric)
import numpy as np
def fuzz_trans(A,n):
    flag=0
    for i in range(0,n):
        for j in range(0,n):
            for k in range(0,n):
                if A[i][k]>=min(A[i][j],A[j][k]):
                    continue
                else:
                    flag=1
    if flag==0:
        return("Transitive relation")
    else:
        return("Not a Transitive relation")

def find_equiv(A,A2,n):
    if np.array_equiv(A2,np.zeros((n,n))):
            for i in range(0,n):
                for j in range(0,n):
                    for k in range(0,n):
                        A2[i][j]=max(A2[i][j],min(A[i][k],A[k][j]))
            if np.array_equiv(A2,A):
                return(A2)
            
            else:
                return(find_equiv(A,A2,n)) 
    else:
        A3=np.zeros((n,n))
        for i in range(0,n):
                for j in range(0,n):
                    for k in range(0,n):
                        A3[i][j]=max(A3[i][j],min(A2[i][k],A[k][j]))
        if np.array_equiv(A2,A3):
            return(A2)
            
        else:
            return(find_equiv(A,A3,n)) 
            
A=np.array([[1,0.83,0.91,0.68,0.98],[0.83,1,0.93,0.6,0.74],[0.91,0.93,1,0.44,0.82]\
            ,[0.68,0.6,0.44,1,0.77],[0.98,0.74,0.82,0.77,1]])
n=5
print("The matrix under consideration to check equivalence relation:\n",A)
print("The given fuzzy relation is ", fuzz_trans(A,n))
if (fuzz_trans(A,n)=="Not a Transitive relation"):
    A2=np.zeros((n,n))
    print("Hence the equivalence matrix is given by \n", find_equiv(A,A2,n))
    


The matrix under consideration to check equivalence relation:
 [[1.   0.83 0.91 0.68 0.98]
 [0.83 1.   0.93 0.6  0.74]
 [0.91 0.93 1.   0.44 0.82]
 [0.68 0.6  0.44 1.   0.77]
 [0.98 0.74 0.82 0.77 1.  ]]
The given fuzzy relation is  Not a Transitive relation
Hence the equivalence matrix is given by 
 [[1.   0.91 0.91 0.77 0.98]
 [0.91 1.   0.93 0.77 0.91]
 [0.91 0.93 1.   0.77 0.91]
 [0.77 0.77 0.77 1.   0.77]
 [0.98 0.91 0.91 0.77 1.  ]]
